### PR TITLE
read api_key from header

### PR DESCRIPTION
**Pull request by lehnerchristian**

### CODE REVIEW

**Comment by thinkh** [comment]
@lehnerchristian or @anita-steiner: Is there any related PR? Why is the api_key suddenly transferred in the header?

**Comment by anita-steiner** [comment]
the api_key was implemented for the tdp_comments --> tdp_comments sets the header and not the arg

**Comment by thinkh** [comment]
Ok, thanks for the explanation.

**Comment by lehnerchristian** [comment]
yes, that's right. I didn't find any usages of the API key and in tdp_comments it was sent via the headers and here the GET parameters (via `.args`) were read. but I'm also open for changing this back to send the API key as GET parameter - would there be any security implications, caching issues, etc?

the following links say it should be put into the Authorization header... see [here](https://stackoverflow.com/questions/5517281/place-api-key-in-headers-or-url) and [here](http://www.bizcoder.com/where-oh-where-does-the-api-key-go)

**Pull request merged**
